- src/openslide-cache.c
- src/openslide-private.h
- src/openslide.c
- src/openslide.h
- test/extended.c
Create a slide handle with a default cache, but allow the user to separately allocate a cache of any size (including zero) and attach it to one or more slide handles.  This allows sharing a cache between slides.  The public API is:
```C
// allocate new cache
openslide_cache_t *openslide_cache_create(int64_t capacity);
// set cache for slide handle, replacing the existing cache
void openslide_set_cache(openslide_t *osr, openslide_cache_t *cache);
// release application's reference to a cache; cache is not freed until
// all attached slides are detached or closed
void openslide_cache_release(openslide_cache_t *cache);
```
For now, don't support resizing an existing cache, nor external caches implemented by the application.  Those features can be added within the existing API if they turn …
> Add exported cache management API

- configure.ac
- m4/visibility.m4
- m4/warnings.m4
Autoconf 2.69 was released in 2012; bump the minimum version to that since we don't test on earlier ones.
> configure.ac: fix Autoconf 2.70 deprecation warnings

- .github/workflows/c.yaml
We [document](https://openslide.org/docs/testsuite/#tips) that xdelta diffs should be kept small, to avoid carrying large blobs in the repository.  Enforce that via CI.
> workflows: check for xdelta diffs larger than 6000 bytes

- test/extended.c
`sleep(3)` requires `unistd.h`.
> test/extended: fix missing include on Windows

- test/driver.in
This got through CI because CI was only unpacking a frozen archive, and not unpacking any tests from scratch.
Fixes #362.
> test/driver: fix test case unpacking on macOS

- .github/workflows/c.yaml
- test/synth.c
`putenv()` is available but `setenv()` [isn't](https://sourceforge.net/p/mingw/mailman/message/35495004/).
Windows CI didn't catch this because it was always building `main` instead of the actual PR content.  Fix that too.
> Fix synthetic test on Windows, and also CI

- test/synth.c
On some systems this is necessary to get the prototype for `putenv()`.
> test/synth: define `_XOPEN_SOURCE`

- Makefile.am
- src/openslide-decode-gdkpixbuf.c
- src/openslide-decode-jpeg.c
- src/openslide-decode-jpeg.h
- src/openslide-decode-png.c
- src/openslide-decode-tiff.c
- src/openslide-decode-tifflike.c
- src/openslide-error.c
- src/openslide-file.c
- src/openslide-hash.c
- src/openslide-jdatasrc.c
- src/openslide-private.h
- src/openslide-util.c
- src/openslide-vendor-hamamatsu.c
- src/openslide-vendor-mirax.c
- test/cases/mirax-index-bad-nonhier-table-base/config.yaml
- test/cases/mirax-index-hier-bad-initial-data-page-pointer/config.yaml
- test/cases/mirax-index-hier-bad-level-pointer/config.yaml
- test/cases/mirax-index-negative-hier-root/config.yaml
- test/cases/mirax-index-nonhier-bad-initial-data-page-pointer/config.yaml
- test/cases/mirax-index-nonhier-bad-table-entry/config.yaml
- test/cases/mirax-slidepos-bad-position/config.yaml
This allows us to add some additional conveniences, such as `GError` returns and automatic retries for short reads.
This should affect all I/O initiated by OpenSlide, except for SQLite.
> Use wrapper functions for all file I/O

- .github/workflows/c.yaml
- configure.ac
- src/openslide-file.c
Test on a variety of distros that we want to keep working.
Notably, we're not testing Debian oldstable, Ubuntu 18.04, and CentOS 7, which in practice means that we're dropping support for them.  The current Debian oldstable will go EOL next month.  Ubuntu 18.04 has not been the current LTS release for two years, and likewise RHEL 8 was released in 2019.  While it's good to preserve some compatibility with LTS distros, we shouldn't maintain very old compatibility constraints forever, and this seems like a good compromise.
Also move the `continue-on-error` flag to job level.  The unconditional `continue-on-error` on `./driver run` caused that step to misleadingly report green, even on OSes where it was failing unexpectedly.  Move the flag to the job level for macOS, which will cause the job …
> workflows: test on Debian stable, Ubuntu 20.04/22.04, CentOS Stream 8/9

- Makefile.am
- src/openslide-vendor-leica.c
- src/openslide-vendor-ventana.c
- test/query.c
- test/try_open.c
- tools/openslide-quickhash1sum.c
- tools/openslide-show-properties.c
- tools/openslide-write-png.c
- Test `openslide_can_open()`
- Fix some incorrect return types on error
- Replace remaining uses of `TRUE`/`FALSE` with `true`/`false`
- Stop mixing allocators in `openslide-write-png`
- Minor tools cleanups
> Minor fixes/cleanups

- src/openslide-vendor-synthetic.c
Don't require doing it by hand in the canonical item description.
> synthetic: automatically add `(not rendered)` to description property

- misc/make-synthetic-item.py
- src/openslide-vendor-synthetic.c
- test/cases/synthetic/config.yaml
Both decoders use `setjmp`/`longjmp` for error handling, which has historically had problems on 64-bit Windows with MinGW.  Let's include it in our smoke tests.
For https://github.com/openslide/openslide-winbuild/pull/49.
> synthetic: test decoding corrupt JPEG and PNG

- .github/workflows/c.yaml
- configure.ac
- misc/make-vmu.py
- src/openslide-decode-gdkpixbuf.c
- src/openslide-decode-png.c
- src/openslide-decode-tiff.c
- src/openslide-decode-tiff.h
- src/openslide-private.h
- src/openslide-util.c
- src/openslide-vendor-aperio.c
- src/openslide-vendor-generic-tiff.c
- src/openslide-vendor-hamamatsu.c
- src/openslide-vendor-leica.c
- src/openslide-vendor-mirax.c
- src/openslide-vendor-philips.c
- src/openslide-vendor-sakura.c
- src/openslide-vendor-synthetic.c
- src/openslide-vendor-trestle.c
- src/openslide-vendor-ventana.c
Also migrate the holdout functions in the PNG and gdk-pixbuf decoders, and convert `make-vmu.py` (for testing VMU support) to Python 3.
Closes #310.
> Migrate vendor drivers to `g_autoptr`

- .github/workflows/c.yaml
Make sure we have the latest package definitions.  We do this on Debian/Ubuntu and implicitly on Fedora/CentOS, so do it on macOS too for consistency.  This fixes a build failure with `macos-11` image 20220807.1, which was built in the middle of Homebrew's transition from libjpeg to libjpeg-turbo.
Also skip installing gcc and GNU Make on macOS.  We're not currently using either of them.
> workflows: `brew update` before installing Mac packages

- .github/workflows/c.yaml
Now that xdelta is [packaged in EPEL 9](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-3db3325f4c), stop using the Copr.
> workflows: install xdelta from EPEL 9

- test/driver.in
Use all available CPUs, but continue reporting test results in sequential order for ease of reference.  This produces long pauses in output while waiting for slower tests.
We still unpack sequentially for now, since any download progress reports would interleave.  Coverage runs are also still done sequentially to avoid corrupting the coverage data.
Also fix Unicode bugs which were causing `coverage` to crash and `exports` to produce no results.
> test/driver: parallelize `run`, `valgrind`, and source rebuilds

- .github/workflows/c.yaml
- src/openslide-decode-jpeg.c
- src/openslide-decode-jpeg.h
- src/openslide-decode-png.c
- src/openslide-decode-tiff.c
- src/openslide-vendor-hamamatsu.c
Fixes macOS CI.  See individual commits for details.
> JPEG and PNG cleanups; fix JPEG error path when compiled with clang

- .github/workflows/c.yaml
Setting matrix flags to `true` means they show up in the job description as `true`, which isn't helpful.  Use text instead.
Also rename the `ignore-fd-leaks` flag, since it actually controls the `CLOEXEC` test and not the FD leak test.
> workflows: use descriptive text for matrix flags

- .github/workflows/c.yaml
- Makefile.am
- configure.ac
- test/driver.in
- test/try_open.c
- test/valgrind.supp
Update suppressions and ignore some warnings out of our control.  Add Valgrind to the Fedora job, but not to the other jobs as we used to do in Buildbot, since the marginal additional value doesn't seem worth the overhead and suppression maintenance.
> Fix Valgrind failures and enable it in CI

- .github/workflows/c.yaml
Fixes `configure` warnings:
./configure: line 7482: cmp: command not found
./configure: line 9571: diff: command not found
> workflows: install diffutils on RPM-based systems

- .github/workflows/c.yaml
- src/openslide.c
pixman 0.38.x produces corrupt output when subpixel rendering is used with the `SATURATE` operator.  This is [fixed](https://gitlab.freedesktop.org/pixman/pixman/-/commit/8256c235) in 0.40.0.  The consequence is pretty bad (blank output in some regions of some slides) so detect it and refuse to open any slide.  Perform a behavior test at runtime, since we might have been compiled with a different version or the distro might have backported a fix.
Run CI with pixman from a Copr for EL 8, and from a PPA for Ubuntu 20.04, until those distro versions are fixed.
See https://github.com/openslide/openslide/issues/278.
> Fail `openslide_open()` on unpatched pixman 0.38.x

- .github/workflows/c.yaml
`ubuntu-latest` is an alias for 22.04 now, so stop hardcoding 22.04.
> workflows: switch the C9S runner back to ubuntu-latest

- .github/workflows/c.yaml
The bug is fixed in `pixman-0.38.4-0ubuntu2` for 20.04.
This reverts commit 692c572dba49c03f8bf52ddf693b10ca267c837e.
xref https://github.com/openslide/openslide/issues/278
> Revert "workflows: install Ubuntu 20.04 pixman from PPA"

- src/openslide-vendor-trestle.c
libtiff 4.5.0 changes `tdir_t` from `uint16_t` to `uint32_t`, causing this warning:
src/openslide-vendor-trestle.c: In function 'trestle_open':
src/openslide-vendor-trestle.c:324:13: error: comparison of integer expressions of different signedness: 'tdir_t' {aka 'unsigned int'} and 'int32_t' {aka 'int'} [-Werror=sign-compare]
324 |     if (dir < overlap_count) {
`overlap_count` doesn't ever store a negative value, so make it unsigned.
> trestle: fix compile warning with libtiff 4.5.0

- test/driver.in
Allow configuring a `_slidedata` directory outside the build directory, which can help avoid accidental cache deletions with `git clean`.
> test/driver: use cache path from `OPENSLIDE_TEST_CACHE` env var if set

- src/openslide-cache.c
- src/openslide-decode-gdkpixbuf.c
- src/openslide-decode-jpeg.c
- src/openslide-decode-png.c
- src/openslide-decode-tiff.c
- src/openslide-decode-tifflike.c
- src/openslide-file.c
- src/openslide-grid.c
- src/openslide-hash.c
- src/openslide-private.h
- src/openslide-util.c
- src/openslide-vendor-aperio.c
- src/openslide-vendor-dicom.c
- src/openslide-vendor-generic-tiff.c
- src/openslide-vendor-hamamatsu.c
- src/openslide-vendor-leica.c
- src/openslide-vendor-mirax.c
- src/openslide-vendor-philips.c
- src/openslide-vendor-sakura.c
- src/openslide-vendor-synthetic.c
- src/openslide-vendor-trestle.c
- src/openslide-vendor-ventana.c
- src/openslide.c
- test/driver.in
- test/mosaic.c
- test/parallel.c
- test/try_open.c
glib deprecated it.
Fixes https://github.com/openslide/openslide/issues/430.
> Drop glib slice allocator

- meson_options.txt
It produces a deprecation warning with Meson 1.1.0.
> meson: don't use string-typed defaults for boolean options

- test/driver.in
Allow overriding the openslide-testdata root URL from the `OPENSLIDE_TESTDATA_URL` environment variable.
In addition, frozen archives include the data needed to produce the mosaic.  Fetch the needed pristine slides before freezing, and before mosaicing if we don't have frozen data, but we don't need to do it before mosaicing from frozen data.
> test/driver: add `OPENSLIDE_TESTDATA_URL`; don't refetch for mosaic if we have frozen data

- src/openslide-grid.c
- src/openslide.c
The simple grid doesn't have overlaps or subpixel offsets, so we don't need to use `CAIRO_OPERATOR_SATURATE` to avoid seams.  Use the default `CAIRO_OPERATOR_OVER` in this case.  On my system this gives a 3x-5x performance improvement in single-threaded `test/parallel`.
For https://github.com/openslide/openslide/issues/440.
> grid: avoid `CAIRO_OPERATOR_SATURATE` in simple grid

- src/meson.build
- src/openslide-private.h
- src/openslide-vendor-philips-tiff.c
- src/openslide.c
There are plans to add a Philips iSyntax driver.  From the perspective of the `openslide.vendor` property these will both be `philips`, but the two drivers will share no code.  Clarify that the existing driver is for the TIFF format.
> Rename "philips" to "philips-tiff" internally

- src/openslide-vendor-dicom.c
This PR enhances the DICOM vendor code to expose 3 openslide properties if present:
- openslide.mpp-x
- openslide.mpp-y
- openslide.objective-power
These are pulled from the lowest level of the pyramid.
---
This is the same PR as #446, but rebased to not depend on #439.
> DICOM: expose magnification properties

- src/openslide-vendor-dicom.c
- test/cases/dicom-tiled-sparse-jpeg/config.yaml
- test/cases/slides.yaml
This PR adds support for the sample Leica DICOM images.
- use a table to map row-major tile positions to DICOM frame numbers
- test DimensionOrganizationType and for "3D" use PerFrameFunctionalGroupsSequence to construct this table
- support uncompressed RGB pixel data
- support RGB JPEG pixel data
> Add support for Leica DICOMs

- common/openslide-common-fail.c
- common/openslide-common.h
- test/extended.c
- test/profile.c
We weren't checking for errors between opening the slide and reading regions, which caused misleading error messages if something failed in between.  Add more granular checks.  This would have clarified the CI failure in https://github.com/openslide/openslide/pull/454#pullrequestreview-1461266163.
cc @jcupitt
> test/extended: add more error checks

- meson.build
- src/openslide-decode-dicom.c
- src/openslide-decode-dicom.h
- src/openslide-vendor-dicom.c
- src/openslide-vendor-synthetic.c
- subprojects/libdicom.wrap
libdicom 0.4 has a simplified API that lets us remove quite a bit of code.
libdicom 0.4 is quite a bit quicker and needs less memory. For example, here's openslide plus libdicom 0.2 on a large Leica DICOM:
```
$ /usr/bin/time -f %M:%e openslide-show-properties 272320e7-5abb-ccac-8f8b-9c2008f53845_114626/1.3.6.1.4.1.36533.1214640142408762111756320324051133413.dcm
openslide.level-count: '4'
openslide.level[0].downsample: '1'
openslide.level[0].height: '84441'
openslide.level[0].tile-height: '256'
openslide.level[0].tile-width: '256'
openslide.level[0].width: '108071'
openslide.level[1].downsample: '4.0000792060552719'
openslide.level[1].height: '21110'
openslide.level[1].tile-height: '256'
openslide.level[1].tile-width: '256'
openslide.level[1].width: '27017'
openslide.level[2].downsample: …
```
> Revise DICOM loader for libdicom 0.4

- src/openslide-vendor-dicom.c
The objective-power metadata item is defined in the optical path sequence:
https://dicom.innolitics.com/ciods/vl-microscopic-image/optical-path/00480105/00480112
This PR fetches objective power from that sequence, not from the main metadata dataset.
With this PR, openslide-show-properties gets the OP correctly from the sample DICOMs I have:
```
$ openslide-show-properties 1.3.6.1.4.1.36533.116129230228107214763613716719238114924751.dcm | grep -i obj
openslide.objective-power: '40'
```
> Get dicom objective-power from optical-path

- .github/workflows/c.yaml
The new Debian stable release is out, and it doesn't leak file descriptors.
> workflows: build with both Debian 11 and 12

- meson.build
- src/openslide-vendor-dicom.c
- subprojects/libdicom.wrap
Properties are named as eg.:
```
dicom.SharedFunctionalGroupsSequence.OpticalPathIdentificationSequence.OpticalPathIdentifier: '0'
```
We don't attach PerFrameFunctionalGroupSequence,
ReferenceImageNavigationSequence or PixelData, since they are huge and only relevant to DICOM image representation internals.
Binary values are NOT attached and appear as eg.
```
dicom.AcquisitionContextSequence.ConceptNameCodeSequence.LongCodeValue: '<binary value of 24 bytes>'
```
Since they can be (potentially) many megabytes in size.
> Add most dicom tags as properties

- src/openslide-vendor-dicom.c
- subprojects/libdicom.wrap
Compression is set solely by transfer syntax.
Fixes https://github.com/openslide/openslide/issues/462
With this PR I see:
```
$ ./driver run
aperio: OK
aperio-33003: OK
...
ventana-truncated-top-level: OK
ventana-untiled-level: OK
Failed: 0/308
```
> Revise dicom compression detection

- src/openslide-vendor-dicom.c
- src/openslide-vendor-synthetic.c
- subprojects/libdicom.wrap
1. Allow DERIVED associated images and DERIVED level 0
2. Support THUMBNAIL associated images
3. Fix color channels in uncompressed RGB images
See https://github.com/openslide/openslide/issues/462
> Improve jp2k DICOM compatibility

- src/openslide-vendor-dicom.c
DICOM directories can often have duplicate levels, perhaps if they have been copied carelessly. This PR tests for duplicate levels during dicom_open().
See https://github.com/openslide/openslide/issues/468
> Prevent duplicate DICOM levels

- src/openslide.c
- test/try_open.c
A NULL `dest` argument has been permitted since `openslide_read_associated_image()` was first added in 85c617fa3e, but the function has always been documented to require a valid pointer.  Unlike in `openslide_read_region()`, there's no real benefit to supporting NULL here, even for testing, since we end up having to allocate the buffer on the caller's behalf.  Since we're making ABI changes anyway, clean this up.
This is an ABI change.
> Forbid NULL `dest` in `openslide_read_associated_image()`

- src/openslide-decode-tiff.c
- src/openslide-decode-tiff.h
- src/openslide-private.h
- src/openslide-vendor-aperio.c
- src/openslide-vendor-dicom.c
- src/openslide-vendor-generic-tiff.c
- src/openslide-vendor-ventana.c
- src/openslide.c
- src/openslide.h
- test/extended.c
This adds two new functions:
```C
bool openslide_icc_profile_size(openslide_t *osr, int64_t *len);
bool openslide_icc_profile_read(openslide_t *osr, void *dest, int64_t len);
```
To get the size of the profile in bytes, and then to read the profile to an allocated buffer. `openslide_icc_profile_size()` returns `true` and sets `len` to 0 if no profile is available for this slide, but no other error was encountered.
These two functions execute two member functions of `_openslide_ops`, which loaders can optionally define.
`openslide-decode-tiff.c` has two helpers. Support is implemented for DICOM, Ventana, Aperio and generic TIFF.
`tes/try_open.c` has a new `profile` flag, and `aperio` and `dicom` have tests. The sample slides for Ventana and generic TIFF don't have embedded profiles, so we …
> Add ICC profile support

- src/openslide.c
- src/openslide.h
- test/cases/aperio/config.yaml
- test/cases/dicom-tiled-full-jp2k-rgb/config.yaml
- test/cases/dicom-tiled-full-jp2k-ycbcr/config.yaml
- test/cases/dicom-tiled-full-jpeg/config.yaml
- test/cases/dicom-tiled-sparse-jpeg/config.yaml
This makes it possible to tell whether an ICC profile was detected by looking at the property output, and also makes it easy for tests to check for a profile.
> Add `openslide.icc-size` property with ICC profile size

- src/openslide-private.h
- src/openslide-vendor-dicom.c
- src/openslide.c
- src/openslide.h
- test/extended.c
- test/try_open.c
There's no requirement that a format uses the same ICC profile for the main image and all associated images.  Add separate APIs for getting associated image ICC profiles, to at least prevent applications from assuming that the main ICC profile can be used everywhere.
When the profile for an associated image is known, drivers should return it, even if it's the same as for the main image.  Do this for DICOM slides, which generally provide the ICC profile in each individual file.  For other formats where we currently support profiles, it's not obvious whether the main profile should also apply to associated images, so return nothing for now.
Also, some ICC docs cleanups and other small fixes.
Fixes https://github.com/openslide/openslide/issues/139.
> Add API for reading associated image ICC profiles

- src/openslide-private.h
- src/openslide.c
- test/cases/dicom-tiled-full-jp2k-rgb/config.yaml
- test/cases/dicom-tiled-full-jp2k-ycbcr/config.yaml
- test/cases/dicom-tiled-full-jpeg/config.yaml
- test/cases/dicom-tiled-sparse-jpeg/config.yaml
Associated images currently aren't represented in properties at all, which isn't entirely helpful for debugging.  Add the width, height, and ICC profile size of each associated image in the form `openslide.associated.$name.{width,height,icc-size}`.
For the prefix, I also considered `openslide.associated-image`.  That would be consistent with OpenSlide's standard terminology, e.g. in C API function names, but in a property listing it'd make the names longer (and arguably less readable) for little actual value.  `associated.label` could be read as "the associated label" so there's some logic to the shorter names.
For the image names I also considered `openslide.associated[$name]`, `openslide.associated["$name"]`, and `openslide.$name`.  We've only used brackets for array indexes, and anyway …
> Add properties for associated image width, height, and ICC profile

- test/cases/aperio-filename-utf8/config.yaml
We no longer run tests via libtool and we no longer support testing from Cygwin, so this can be re-enabled.  At the moment we don't run tests at all on Windows, so this won't actually prove anything yet, but in due course it will.
This reverts commit 98b0e80507fb89fb37fb8be74a394a8dae11ef7e.
> Revert "test: Disable aperio-filename-utf8"

- src/openslide-vendor-dicom.c
Log a message under the `search` debug flag when ignoring duplicate files.
The driver debug code generally reports parameters that are available via OpenSlide properties or a DICOM dumper, plus pointer values.  Now that the driver is reasonably stable, clean up this code.
> dicom: add debug message when ignoring duplicate files; drop debug code

- src/openslide-grid.c
- src/openslide.c
It turns out that it introduces seams after all.  Revert it for now.
Fixes https://github.com/openslide/openslide/issues/483.
This reverts commit 241a82751d1ba3cc62f01c4ff68f518d8bf18d02.
> Revert "grid: avoid CAIRO_OPERATOR_SATURATE in simple grid"

- src/openslide-vendor-dicom.c
Fail detection on non-WSI DICOM files, and require RGB photometric interpretation for uncompressed pixel data.
> dicom: add some extra checks

- README.md
libdicom 1.0 isn't out yet, but that's what we'll require by release time, so go ahead and list it now.
Also, sort the library dependencies.  The existing list tries to use some kind of logical ordering, but in truth no such ordering exists.  Give up and use alphabetical order.  However, keep Meson at the top, since the build tool is the first thing users will need.
> README: add DICOM format; note ICC profile support

- tools/meson.build
- tools/openslide-quickhash1sum.1.in
- tools/slidetool-icc.c
- tools/slidetool-image.c
- tools/slidetool-prop.c
- tools/slidetool-slide.c
- tools/slidetool.1.in
- tools/slidetool.c
- tools/slidetool.h
We haven't had a stable release with `slidetool`, so we can still do some reorganization.
> Add `slidetool slide {open,vendor}`; move `icc` and `quickhash1` out of top level

- test/driver.in
[Tell backup software](https://bford.info/cachedir/) that the cache directory doesn't need to be backed up.
> test/driver: add `CACHEDIR.TAG` file to cache directory

- common/openslide-common-fd.c
First detected in https://github.com/microsoft/vcpkg/pull/33088
Documented to come from `<io.h>` in https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/get-osfhandle?view=msvc-170
```
D:\buildtrees\openslide\src\v3.4.1-a70eeb2621.clean\test\test-common.c(51,25): error: call to undeclared function '_get_osfhandle'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
HANDLE hdl = (HANDLE) _get_osfhandle(fd);
```
> Add missing <io.h> for '_get_osfhandle'.

- src/openslide-features.h
- src/openslide.h
1cae453a33 conditionalized use of `stdbool.h` so the public headers could be included from MSVC, which didn't support `stdbool.h` at the time. However, VS 2013 added support.  Assume the user has a compiler at least that new, and drop the conditional.
> Require `stdbool.h` in `openslide.h`

- src/openslide-decode-tifflike.c
There doesn't appear to be any reason to make them signed.
> tifflike: change some `populate_item()` variables to unsigned

- meson.build
The `CLOEXEC` check is our only use of `compiler.run()`, which breaks cross-compilation when the build machine can't run the host's binaries (except on Windows, which we special-cased).  In fact, all modern versions of Linux (glibc and musl) and of the BSDs support the `e` flag.  Drop the test program and just look at the host OS string.
Reported by @alanocallaghan in openslide/openslide-winbuild#96.
> meson: drop `fopen` `CLOEXEC` test program; just look at host OS

- meson.build
- src/openslide-vendor-dicom.c
- subprojects/libdicom.wrap
Sparse DICOMs can have missing frames.  Detect these and skip rendering.
This also bumps libdicom to rc2 to get improved sparse tile support.
> dicom: handle missing frames

- .github/workflows/c.yaml
We only build docs on Fedora.  Avoid installing doxygen elsewhere to ensure we don't require it.
> workflows: only install doxygen when building docs

- src/openslide-dll.rc.in
GNU windres does not treat hyphens as separators. However, llvm-rc or MSVC's rc.exe treats them as separators, causing a build error on these toolchains if the value is not quoted.
See: https://github.com/mstorsjo/llvm-mingw/issues/67
> Ensure that the RT_MANIFEST value is quoted

- .github/workflows/c.yaml
`pixman-0.38.4-3.el8` fixes the rendering issue.
This reverts commit 0fd396e4a33452adb0e534b04f057a0158b5252b.
> Revert "workflows: install EL8 pixman from Copr"

- meson.build
- meson_options.txt
- src/openslide-vendor-synthetic.c
- src/openslide.c
- subprojects/.gitignore
- subprojects/libdicom.wrap
- test/cases/dicom-tiled-full-jp2k-rgb/config.yaml
- test/cases/dicom-tiled-full-jp2k-ycbcr/config.yaml
- test/cases/dicom-tiled-full-jpeg/config.yaml
- test/cases/dicom-tiled-sparse-jpeg/config.yaml
Now that the libdicom API has stabilized and DICOM support is no longer under rapid development, require libdicom, so every OpenSlide installation will support the same formats.
For now, we'll continue shipping the Meson wrap as a convenience; we can drop it once libdicom is broadly available in package managers.
> Update to libdicom 1.0.1 from wrapdb and make it mandatory

- src/openslide-private.h
Add a definition for `_NO_W32_PSEUDO_MODIFIERS` so that `windows.h` will not define the `IN`/`OUT` macro. Resolves a compilation error with a patched libjpeg-turbo header carried in MSYS2.
<details>
<summary>Details</summary>
```
FAILED: src/libopenslide-0.dll.p/openslide-vendor-mirax.c.obj 
/data/mxe/usr/bin/x86_64-w64-mingw32.shared.posix.all-clang -Isrc/libopenslide-0.dll.p -Isrc -I../openslide-openslide-e3908b0/src -I. -I../openslide-openslide-e3908b0 -I/data/mxe/usr/x86_64-w64-mingw32.shared.posix.all/include/glib-2.0 -I/data/mxe/usr/x86_64-w64-mingw32.shared.posix.all/lib/glib-2.0/include -I/data/mxe/usr/x86_64-w64-mingw32.shared.posix.all/include/gdk-pixbuf-2.0 -I/data/mxe/usr/x86_64-w64-mingw32.shared.posix.all/include/libpng16 …
```
> Prevent pseudo modifiers from being defined

- src/openslide.h
- Avoid some circumlocution by saying "device color space"
- Hint at what the ICC profile should be used for
- Clarify "ICC profile" to "ICC color profile"
> openslide.h: improve wording of ICC profile docs

- src/openslide-vendor-aperio.c
Some Aperio slides have a floating-point `AppMag` such as `40.000000`. In the samples I've seen, the `ImageDescription` mentions both `Aperio Image Library` and `Leica SCN`.  One such file is [TCGA-3C-AALI-01Z-00-DX2.CF4496E0-AB52-4F3E-BDF5-C34833B91B7C.svs](https://portal.gdc.cancer.gov/files/6a7477b1-86f3-473f-9bf1-174a758142e9).
Support transcribing such `AppMag`s to `openslide.objective-power`.  The value will still be stored as an integer if it can be represented in one.
Fixes: https://github.com/openslide/openslide/issues/247
Fixes: https://github.com/openslide/openslide/issues/332
> aperio: allow floating-point objective power

- misc/dicom-quickhash.py
- src/openslide-vendor-dicom.c
- test/cases/dicom-tiled-full-jp2k-rgb/config.yaml
- test/cases/dicom-tiled-full-jp2k-ycbcr/config.yaml
- test/cases/dicom-tiled-full-jpeg/config.yaml
- test/cases/dicom-tiled-sparse-jpeg/config.yaml
The purpose of the quickhash is to `uniquely identify a particular virtual slide, but [not] to detect file corruption or modification`.  Most slide formats don't include unique identifiers, so we usually have to construct one from metadata that collectively is unique to a slide.
In the case of DICOM, there are already unique identifiers for entities at various conceptual levels.  Those identifiers refer to the conceptual entity, not its exact representation.  For example, the SOP Instance UID doesn't change if the pixel data or metadata are altered in certain ways that don't change the instance's notional semantics.
Rather than second-guessing DICOM's approach to entity naming, adopt it.  That requires us to pick a UID to hash.  The Acquisition UID is too general (two recompressions of …
> dicom: support quickhash-1

- .github/workflows/c.yaml
We've only been testing i386 via the Windows builds, which only run the smoke test.
Also install libdicom from Homebrew on macOS.
> workflows: test i386 build on Debian

- tools/openslide-quickhash1sum.1.in
- tools/openslide-show-properties.1.in
- tools/openslide-write-png.1.in
- tools/slidetool.1.in
groff &ge; 1.23.0 remaps unescaped `-` characters to Unicode HYPHEN, not ASCII dash.  For dashes that are part of command-line arguments, this causes misbehavior if the arguments are pasted into a shell.  Escape all affected dashes.
See [article](https://lwn.net/Articles/947941/).
> tools: escape dashes in man pages that need escaping

- .github/workflows/c.yaml
Use API introduced in openslide/openslide-winbuild#164.
> workflows: explicitly request Windows container

- .github/ISSUE_TEMPLATE/release.md
Update Fedora and check that it propagated to the Copr before announcing. Also announce to forum.image.sc.
> templates/release: procedure updates

- src/meson.build
- src/openslide-decode-jp2k.c
- tools/meson.build
openslide-bin can use this to package a bdist ZIP from Meson.
> meson: allow parent project to find executables and public headers

- meson.build
- meson_options.txt
- src/meson.build
On macOS, openslide-bin needs to use a linker option to filter out non-OpenSlide exported symbols.  It can't set the option globally because that would break OpenSlide Java, and can't set a per-project option because Meson doesn't support that.  Add a private option to do the filtering until Meson provides syntax for this.
> meson: add a private option to filter out non-OpenSlide symbols

- meson.build
`G_DEFINE_AUTOPTR_CLEANUP_FUNC` is always defined, since omitting it is harmless.  `g_autofree` is conditionally defined, since omitting it would cause leaks.  Check for that instead, and produce a somewhat clearer error if the check fails.
Closes https://github.com/openslide/openslide/issues/536.
> meson: fix detection of `g_autoptr` support

- .gitattributes
- .github/workflows/c.yaml
- .pre-commit-config.yaml
- misc/decode-trestle-tile-position.py
- misc/reconstruct.m
- test/parallel.c
OpenSlide Python and now openslide-bin already use [pre-commit](https://pre-commit.com/).  Most of those checks are Python-focused, but there are some useful language-independent ones.  Enable the latter, and convert the existing CI checks for overlarge test cases and for uninitialized autoptrs to pre-commit checks.
> Add basic pre-commit checks; move some existing CI checks into pre-commit

- .github/workflows/c.yaml
We only need to unlink and relink installations of Python, not other packages with `python` in their names.
> workflows: don't relink Brew installations of random Python packages

- src/openslide-decode-gdkpixbuf.c
The failure can occur if the requested gdk-pixbuf decoder (currently we only use BMP) is built as a loadable module, packaged separately, and not installed.  Give the user a hint that they may need to install it.
Closes: https://github.com/openslide/openslide/issues/544
> gdkpixbuf: add hint to error message on context creation failure

- meson.build
- test/driver.in
- test/meson.build
- test/try_open.c
- test/valgrind.supp
We still use it for the nightly s390x big-endian run.  Don't run it in GitHub Actions, though, to save runtime.
Partially reverts #554.
> test/driver: re-add valgrind command

- .github/workflows/c.yaml
Use the new `save-always` option to save pristine slides even after a CI failure.
> workflows: update actions/cache to v4

- .pre-commit-config.yaml
- src/openslide-decode-sqlite.c
- src/openslide-decode-tiff.c
- src/openslide-file.c
- src/openslide-jdatasrc.c
- src/openslide-private.h
- src/openslide-util.c
- src/openslide-vendor-synthetic.c
Preprocessor macros are somewhat clunky as a way to prevent use of forbidden functions.  Now that we have pre-commit checks, use those instead.  Allow forbidden function calls in wrapper implementations by ignoring call sites with `ci-allow` in a comment on the same line.
> Replace `_OPENSLIDE_POISON()` with pre-commit check

- src/openslide-vendor-dicom.c
- test/cases/dicom-dual-bigtiff-file-extension/config.yaml
If the specified slide file has a TIFF filename extension, assume the user wants to read it as TIFF, and have the DICOM driver ignore it.
> dicom: ignore dual-personality TIFF files with `.tif`/`.tiff` file extension

- .github/workflows/c.yaml
pip has started throwing `This environment is externally managed` errors when installing system-wide.  These days the macOS build uses Python from Homebrew, so switch to installing these packages from Homebrew too.
> workflows: install Requests and PyYAML from Homebrew on macOS

- src/openslide-decode-tiff.c
- src/openslide-private.h
- src/openslide-util.c
- src/openslide-vendor-synthetic.c
Opening and closing an `_openslide_file` for every TIFF read is needlessly inefficient.  Once the file is opened, hold it open until the `_openslide_cached_tiff` is released, since that object is single-threaded and will be released before OpenSlide returns to its caller.  Don't eagerly open the file when the `_openslide_cached_tiff` is acquired, since the needed pixels may be in cache and we may not need to read from the TIFF at all.
> tiff: hold file handle open until `cached_tiff` is released

- common/meson.build
- common/openslide-common-fd.c
- common/openslide-common.h
- src/openslide-decode-dicom.c
- src/openslide-decode-dicom.h
- src/openslide-vendor-dicom.c
- test/extended.c
- test/meson.build
- test/try_open.c
OpenSlide generally avoids holding file descriptors open when idle, allowing the application to cache OpenSlide handles without consuming FDs.  Have the DICOM driver close FDs when not using them.  Add tests to ensure FDs aren't left open after opening a slide or reading regions or associated images.
> Don't hold DICOM file descriptors open; add tests for stray FDs

- src/openslide-decode-jpeg.c
- src/openslide-decode-jpeg.h
- src/openslide-vendor-dicom.c
Hello everyone, this is a strange PR, here's the referring issue:
https://github.com/ImagingDataCommons/libdicom/issues/80
SVS doesn't set the component ids correctly in their JPEG tiles and readers are supposed to override the JPEG colorspace with the photometric interpretation of the enclosing container.  openslide does this in `decode_jpeg()` in `openslide-decode-tiff.c`.
When bioformats converts SVS to DICOM, it just copies the JPEG tiles over directly and does not fix the component ids. When openslide reads the DICOM file, libjpeg guesses YCbCr for the file encoding (it's really RGB), does the YcbCr -> RGB conversion when it should not, and you get crazy colours.
This PR adds a check for JPEG tiles with unknown component ids and only in this case overrides the `jpeg_color_space` …
> dicom: set JPEG decode colorspace from DICOM metadata

- test/extended.c
When creating a vendor driver, developers may forget to either populate or disable the quickhash-1.  Add a check for this.
> test/extended: check for unpopulated quickhash-1

- .pre-commit-config.yaml
`ato*()` doesn't report errors, and `strto*()` can vary behavior based on system locale.
> pre-commit: forbid more numeric parsing functions

- .github/workflows/c.yaml
Avoids deprecation warnings:
Warning: python-requests has been deprecated because it does not meet homebrew/core's requirements for Python library formulae!
Warning: python-charset-normalizer has been deprecated because it does not meet homebrew/core's requirements for Python library formulae!
Warning: python-idna has been deprecated because it does not meet homebrew/core's requirements for Python library formulae!
Warning: python-urllib3 has been deprecated because it does not meet homebrew/core's requirements for Python library formulae!
> workflows: install Requests with pip on macOS

- .pre-commit-config.yaml
- test/parallel.c
- test/profile.c
- tools/slidetool-icc.c
- tools/slidetool-image.c
- tools/slidetool-util.c
Some prohibited functions have replacements provided by glib, not by OpenSlide, so we can enforce the prohibition outside of OpenSlide proper.  Split the prohibited-function test into two pieces, and enforce the generic part everywhere except `misc/`, which contains one-off development scripts.
Prohibit `strerror()` and `strerror_l()`, which are not thread-safe; the libc memory allocator, since we use glib; and the glib slice allocator, which is deprecated upstream.
> pre-commit: check all C code for prohibited funcs without wrappers; prohibit more funcs

- .github/ISSUE_TEMPLATE/release.md
- .github/workflows/c.yaml
Run `meson dist` alongside the extra checks in every build, because it's a good idea to test this and because the build job already installs the dependencies for `meson setup`.  Archive the artifact, then conditionally run a second job to create the release.  Leave the release in draft state so a longer-form release description can be added before publishing.
This uses the same release-job pattern as OpenSlide Python, rather than starting a second workflow upon completion of the build workflow.  This results in a skipped job in every PR's job list, but allows the passing of output variables between jobs.
Also fix Windows CI builds from a tag.  This was already broken in 4.0.0, but the CI failure wasn't noticed at the time.
> workflows: automatically create draft GitHub release when tagged

- .github/workflows/c.yaml
`test/driver sanitize` hits `ld.bfd` segfaults on Fedora 40 when linking executables.  This might have something to do with our specific build flags, so we might need to troubleshoot further if there's no upstream interest.  For now, just get CI working.
https://bugzilla.redhat.com/show_bug.cgi?id=2278106
> workflows: pin to Fedora 39 to avoid `ld` segfault during sanitize

- misc/imhex/hamamatsu-vms-opt.hexpat
- misc/imhex/mirax-index.hexpat
- misc/imhex/mirax-position.hexpat
Automatically decompress position array if needed.
Also switch all ImHex patterns from `#include` to the new `import` statement.
> misc/imhex/mirax-position: support StitchingIntensityLevel

- .github/workflows/c.yaml
Pending a fix for [RHBZ 2278106](https://bugzilla.redhat.com/show_bug.cgi?id=2278106), link the sanitize binaries with `lld`.  This lets us switch back to Fedora 40.
> workflows: link sanitize run with `lld` on Fedora to work around segfault

- .github/workflows/c.yaml
Fix `ld` crash during sanitize.
https://bugzilla.redhat.com/show_bug.cgi?id=2278106
> workflows: install binutils from Fedora updates-testing

- misc/imhex/hamamatsu-vms-opt.hexpat
- misc/imhex/hamamatsu-vmu-ngr.hexpat
Whenever the VMS optimisation offset decreases, we've switched to the next JPEG.  Make each JPEG a separate struct in the output.
> misc/imhex: add VMU NGR; split VMS optimisations into a struct per JPEG

- .github/workflows/c.yaml
The fix has migrated to `updates`.
This reverts commit 476edad048a83b9018b6a4d0ecda983e178320aa.
> Revert "workflows: install binutils from Fedora updates-testing"

- src/openslide-vendor-zeiss.c
Avoid spurious maybe-uninitialized warning with EL 8 GCC.
> zeiss: initialize `max_downsample` out-argument earlier

- meson.build
- meson_options.txt
- test/meson.build
openslide-bin dropped support for 32-bit Windows, so we won't be running this check in CI.  In fact, we haven't run any Windows tests in a long time (https://github.com/openslide/openslide/issues/367) and probably no one else is either.
> meson: drop support for testing with 4-byte stack alignment on Win32

- .github/workflows/c.yaml
The latter is now an alias for the former.  Switch back so we get future OS updates.
> workflows: switch from `macos-14` to `macos-latest`

- .pre-commit-config.yaml
- src/openslide-decode-dicom.c
- src/openslide-decode-gdkpixbuf.c
- src/openslide-decode-jpeg.c
- src/openslide-decode-png.c
- src/openslide-decode-tiff.c
- src/openslide-decode-tifflike.c
- src/openslide-file.c
- src/openslide-hash.c
- src/openslide-jdatasrc.c
- src/openslide-private.h
- src/openslide-util.c
- src/openslide-vendor-hamamatsu.c
- src/openslide-vendor-mirax.c
- src/openslide-vendor-zeiss.c
- test/cases/aperio-truncated-top-level/config.yaml
- test/cases/generic-tiff-truncated-top-level/config.yaml
- test/cases/hamamatsu-ndpi-truncated-top-level/config.yaml
- test/cases/hamamatsu-vms-jpeg-no-marker-length/config.yaml
- test/cases/hamamatsu-vms-jpeg-premature-eoi/config.yaml
- test/cases/hamamatsu-vms-jpeg-truncated-data/config.yaml
- test/cases/hamamatsu-vms-jpeg-truncated-header-2/config.yaml
- test/cases/hamamatsu-vms-jpeg-truncated-header/config.yaml
- test/cases/leica-truncated-top-level/config.yaml
- test/cases/mirax-bmp-truncated-image/config.yaml
- test/cases/mirax-data-truncated-top-level/config.yaml
- test/cases/mirax-index-nonhier-associated-bad-offset/config.yaml
- test/cases/mirax-slidepos-truncated/config.yaml
- test/cases/trestle-truncated-top-level/config.yaml
- test/cases/ventana-truncated-top-level/config.yaml
Many `_openslide_fread()` callers want to fail unless the specified number of bytes is read.  Add a helper for this.  For the remaining callers, add a `GError **` argument so the caller can detect the difference between EOF and an I/O error.
Add more detail to various VFS error messages, avoiding some `g_prefix_error()` calls in callers.
> Add GError argument to `_openslide_fread()`; add `_openslide_fread_exact()`

- src/openslide-file.c
- src/openslide-private.h
- src/openslide-vendor-dicom.c
`g_dir_read_name()` can fail; we need to check `errno` for the error.
> Add `GError **` argument to `_openslide_dir_next()`

- .github/workflows/c.yaml
CentOS Stream 8 will shortly be EOL, and AlmaLinux 8.10 includes a fixed pixman.
> workflows: switch from CentOS Stream 8 to AlmaLinux 8

- misc/imhex/hamamatsu-ndpi.hexpat
Based on upstream ImHex TIFF pattern as of commit WerWolv/ImHex-Patterns@10bf1c76cf, licensed under GPLv2.  Support for 64-bit NDPI based on work by @ntrahearn.
> misc/imhex: add Hamamatsu NDPI pattern

- .github/workflows/c.yaml
The Fedora job runs a number of extra tests.  By declaring it separately, we duplicate some code (mainly dependency installation) but we also drop a number of conditionals.  More importantly, by sequencing the other jobs after the Fedora one, we can avoid building the pristine cache multiple times in parallel when missing.
Fail the subsequent jobs if the cache can't be restored.  Install the `zstd` command-line tool to avoid an obscure restore failure in `actions/cache`.
> workflows: run Fedora job before other build jobs

- .pre-commit-config.yaml
Avoid manually copying strings to unbounded buffers.  Parse numbers with OpenSlide's existing parse functions, using their existing error checking conventions.
Prompted by #625; cc @peterchen183
> pre-commit: forbid `stpcpy`, `strcat`, `strcpy`, `sscanf`

- .github/workflows/c.yaml
The option never actually worked, and is being deprecated upstream.  We could implement it ourselves with separate `actions/cache/save` and `actions/cache/restore` invocations, but don't bother for now.
> workflows: drop `save-always` from `actions/cache` invocation

- test/meson.build
- test/synth.c
- tools/meson.build
- tools/slidetool-test.c
- tools/slidetool.c
- tools/slidetool.h
Provide a more accessible way to run self-tests in an installed OpenSlide, rather than `OPENSLIDE_DEBUG=synthetic slidetool prop list ""`.  Omit it from the man page for now, and hide the `test` subcommand from the top-level subcommand list by omitting the summary string.
Have `meson test` run self-tests via the new subcommand.
> test/synth: move to `slidetool test deps`

- .github/workflows/update-check.yml
Forbid maintainers from modifying automatic PRs, since the next workflow run will overwrite their changes.
> workflows: update `peter-evans/create-pull-request` to v7

- .github/workflows/c.yaml
Use GitHub's paid support for ARM64 runners, pending the free offering scheduled for later this year.
> workflows: test on Debian 12 aarch64

- .github/workflows/c.yaml
Avoids error:
Error: pyyaml has been disabled because it does not meet homebrew/core's requirements for Python library formulae! It was disabled on 2024-10-06.
> workflows: install PyYAML with pip on macOS

- .github/workflows/c.yaml
GitHub is [deprecating](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/) the `ubuntu-20.04` image.
> workflows: switch Ubuntu 20.04 job to container

- .github/workflows/c.yaml
[Drop](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/) the paid runner.
> workflows: switch ARM job to publicly-available runner

- common/meson.build
- meson.format
- src/meson.build
- tools/meson.build
Allow `meson format` to automatically sort lists of filenames.
Drop the redundant `sort_files` format option.  Notwithstanding the Meson docs, `sort_files` has always defaulted to `true`.
> meson: convert filename arrays to `files()`

- .pre-commit-config.yaml
- misc/test.c
- pyproject.toml
More about codespell: https://github.com/codespell-project/codespell .
I personally introduced it to dozens if not hundreds of projects already and so far only positive feedback.
CI workflow has 'permissions' set only to 'read' so also should be safe.
> Add codespell pre-commit check

- README.md
- meson.build
- subprojects/libdicom.wrap
- test/cases/dicom-level-bad-frame/config.yaml
- test/cases/dicom-primary-bad-metadata/config.yaml
Also define `HAVE_DICOM_GET_FRAME_NUMBER`, we'll need it very shortly for DICOM catenation support.
> bump libdicom to v1.2.0

- .github/workflows/c.yaml
- src/openslide-decode-tifflike.c
GCC 15 in Fedora 42 introduces a new libdicom build warning.  Disable `werror` for libdicom in CI until this is fixed.
clang 20 AddressSanitizer throws `dynamic-stack-buffer-overflow` errors on `fread()`'s write to `buf`, though the buffer size appears to be correct.  Work around this by converting `buf` to a fixed-length array.  We need 8 bytes at most, so the VLA isn't really necessary.
> Fedora 42 CI fixes

- .github/workflows/c.yaml
We produce warnings on older Meson versions because `install_tag` isn't supported before 0.60.  For now, only check for warnings in the primary test job.
> workflows: build with `--fatal-meson-warnings` on Fedora

- .github/workflows/c.yaml
- .pre-commit-config.yaml
- meson.build
- pyproject.toml
- src/meson.build
- test/driver.in
After May 31, Ubuntu 20.04 will no longer be under standard security maintenance.
Python 3.8 is EOL and Ubuntu 20.04 is the last officially-supported distro that requires it.
> Drop support for Ubuntu 20.04 and Python 3.8

- .github/workflows/c.yaml
Prevent Homebrew from producing workflow annotations like:
> workflows: silence Homebrew annotations about pre-existing packages

- .github/workflows/c.yaml
It was an Autoconf dependency and is no longer needed.
> workflows: drop diffutils

- test/driver.in
- test/extended.c
- test/meson.build
Add OpenSlide to the HTTP User-Agent and enable connection reuse.  Also some minor cleanups broken out of a larger patch series.
> test: minor cleanups

- .github/workflows/c.yaml
- .github/workflows/vcpkg-cache.yml
- scripts/vcpkg-install.sh
- test/driver.in
- tools/slidetool-test.c
Test building on Windows with MinGW GCC.  We'll eventually run the test suite too.  Retain the openslide-bin Windows job, since it's useful to test that we can build release binaries, but rename it for consistency.
Install our dependencies with vcpkg.  With a cold cache, these take over 30 minutes to build.  We could use GitHub Actions caching, but that would age out unless CI ran on Git main every 7 days, and it wouldn't help forks.  vcpkg also supports per-package caching using the GitHub Packages NuGet registry; use that instead.  Push to the registry on every build on main, and also from a weekly scheduled job to keep the cache fresh.  PRs and forks can read from the registry but cannot update it.
Fix `slidetool test deps` on Windows.
> workflows: add Windows build using Windows runner and vcpkg

- .pre-commit-config.yaml
- src/openslide-cache.c
- src/openslide-decode-tifflike.c
- src/openslide-grid.c
- src/openslide-private.h
- src/openslide-vendor-aperio.c
- src/openslide-vendor-dicom.c
- src/openslide-vendor-generic-tiff.c
- src/openslide-vendor-hamamatsu.c
- src/openslide-vendor-leica.c
- src/openslide-vendor-mirax.c
- src/openslide-vendor-philips-tiff.c
- src/openslide-vendor-sakura.c
- src/openslide-vendor-trestle.c
- src/openslide-vendor-ventana.c
- src/openslide-vendor-zeiss.c
- src/openslide.c
- test/extended.c
Calling a `void (struct foo *)` function through a `void(*)(void *)` function pointer is apparently UB and Clang UBSan has [started complaining about it](https://reviews.llvm.org/D148827).  We often do this with `GDestroyNotify`, but UBSan doesn't catch it because we don't test with an instrumented glib.
Add macros to define and reference a `GDestroyNotify` wrapper for a typed free function.  Use them consistently, both where we were incorrectly casting to `GDestroyNotify` and where we had free functions taking void pointers.
Have pre-commit check for `GDestroyNotify` casts.
> Add and use macro defining `GDestroyNotify` wrapper function

- meson.build
conda-forge builds SQLite on Windows using SQLite's `Makefile.msc`, which doesn't install a `.pc` file.
> meson: support SQLite on Windows without pkg-config

- src/meson.build
Meson defaults to omitting the `lib` library prefix on Windows except when building with MinGW, producing `openslide-1.dll`.  OpenSlide Java, OpenSlide Python, and other bindings assume the library is `libopenslide-1.dll`, since that's what openslide-bin ships.  Ensure we use that name.
> meson: use `lib` library prefix when building on Windows
